### ISSUE TITLE
Warning "Please upgrade Nix to 2.7 or later" appears on current versions of Nix.

### ISSUE THREAD

**Issue by nadir-ishiguro** [peterldowns/nix-search-cli#10]
Hi, it's me again. Still happily using your tool. Thanks again. 

The only thing bothering me is that including your flake in my config leads to the mentioned warning appear each time it is called via eg `nix-rebuild`. 

I'm not familiar if that is intentional or if there is some underlying logic that's supposed to check the Nix version and only warn if it's not up to date. 

I'm using the current versions of the unstable and 23.05 channels respectively.

**Comment by peterldowns** [comment]
Thanks for bringing this up, that's a cargo-culted warning and I don't think it's necessary. I should be able to safely remove it.

Here's the commit that introduced the warning:

https://github.com/peterldowns/nix-search-cli/commit/a9c3d9128e4cc2f739c3ef24e0c515beaf636d8c

which cites the original from 

https://github.com/NixOS/nixos-search/blob/af6a59015ca81dd361719cdfaaecce1207cdab3e/flake.nix

Can you tell me what version of Nix you're on, and whether or not this package works for you? If it does, and you're on a version less than 2.7, then I think I can safely remove the warning.

If for some reason you're on < 2.7 *and* this package is uninstallable for you, then I'll leave the warning in place.

**Comment by nadir-ishiguro** [comment]
I'm on Nix 2.17 and haven't used your flake with anything older than 2.15. Both of them have no issues when I replace the warnToUpgrade parts with the respective settings before the commit you linked. 

The warning disappears and everything seems to work great. 

I personally believe the benefit of removing the warning for the majority of flake users that are likely to be on more modern Nix version outweighs the chance of breakage for the minority that are using versions below 2.7.

**Comment by peterldowns** [comment]
Sweet. I agree. I'll update this shortly, thanks for the solid feedback.

**Comment by nadir-ishiguro** [comment]
Thank you for being so responsive and of course for nix-search-cli!

**Comment by peterldowns** [comment]
Thank you, seriously, for using it and for writing in. Always happy to hear that someone is using software I wrote :) 

The problem should be resolved by https://github.com/peterldowns/nix-search-cli/commit/f3f1c53c72dadac06472a7112aeb486ab5dda695
