### ISSUE TITLE
Search in options too?

### ISSUE THREAD

**Issue by FliegendeWurst** [peterldowns/nix-search-cli#11]
I realize this is a "CLI for searching **packages** on search.nixos.org", but there are a lot of packages that work better when their NixOS option is enabled.

For example, `nix-search steam` only returns the packages related to Steam. To properly use Steam on NixOS you'd need to set `programs.steam.enable = true`.

**Comment by peterldowns** [comment]
Feel free to submit a PR, happy to add support for it but as I don't use NixOS I'm not going to implement this myself.

**Comment by tjkirch** [comment]
This would be very useful; it's kind of a newbie trap to only install the package and not look at the available options that would integrate the package into the system.

Could this issue be left open to represent that this is useful work, even if you don't plan to do it yourself?

**Comment by gshpychka** [comment]
@peterldowns why was this closed as completed? Was this implemented?

**Comment by peterldowns** [comment]
@gshpychka per my earlier comment, I don't use nixOS and don't need options search, but I'd be happy to accept a PR if you want to send one.

**Comment by peterldowns** [comment]
@tjkirch 

> Could this issue be left open to represent that this is useful work

It's not useful to me, but if you send a PR it will show up as an open issue and I'll happily review and help you get it merged.

**Comment by gshpychka** [comment]
> @gshpychka per my earlier comment, I don't use nixOS and don't need options search, but I'd be happy to accept a PR if you want to send one.

Right, but doesn't that mean that the issue is still unresolved? If you want to close it, it would make more sense to close it as Not planned, not as Complete

**Comment by tjkirch** [comment]
> Right, but doesn't that mean that the issue is still unresolved? If you want to close it, it would make more sense to close it as Not planned, not as Complete

Neither is really accurate - complete tends to mean the feature is available, and not planned tends to mean it won't be. It's not my project, of course, but I think it would make sense to have the issue open and apply a "contributions welcome" label, or something similar.

**Comment by peterldowns** [comment]
OK, thanks for your feedback. If you send a PR I will take a look.
