### ISSUE TITLE
Package sets

### ISSUE THREAD

**Issue by tjkirch** [peterldowns/nix-search-cli#12]
One of the features I love on the NixOS Search page is Package Sets.  After searching for a term, you can restrict the package set from which you want to see results.  For example, if I know I want a system program and not a Python module or kernel module, I can select "No package set" and get a much shorter list.  Would it be possible to support that?

I can imagine that one challenge regarding the interface for this would be how the user enters the package set they want; do they have to know the exact string from the website?  That seems like it'd be a good start; perhaps the program could list the most common sets in the help text.  Maybe the program could also support shorter aliases for common package sets, like "kde" for "kdePackages", "ruby" for "rubyPackages", etc.

As a particular point, I think "No package set" is so useful that it deserves a dedicated argument.

**Comment by peterldowns** [comment]
Great suggestion. Yes, if the NixOS search website does it, we can do it to. I'll get around to looking at this eventually but if you beat me to it, I'd happilly accept a PR!

**Comment by peterldowns** [comment]
> I can imagine that one challenge regarding the interface for this would be how the user enters the package set they want; do they have to know the exact string from the website? That seems like it'd be a good start; perhaps the program could list the most common sets in the help text.

This is a very good idea and I'm +1 on implementing it this way. Any deviation from the syntax / symbols used by the web search page is probably just asking for trouble, so I'm -1 on aliases / shorthand unless there is significant user interest.

**Comment by peterldowns** [comment]
Here's an example request body that [filters by "no package set"](https://search.nixos.org/packages?channel=23.11&from=0&size=50&buckets=%7B%22package_attr_set%22%3A%5B%22No%20package%20set%22%5D%2C%22package_license_set%22%3A%5B%5D%2C%22package_maintainers_set%22%3A%5B%5D%2C%22package_platforms%22%3A%5B%5D%7D&sort=relevance&type=packages&query=markdown)

```json
{
	"aggs": {
		"all": {
			"aggregations": {
				"package_attr_set": {
					"terms": {
						"field": "package_attr_set",
						"size": 20
					}
				},
				"package_license_set": {
					"terms": {
						"field": "package_license_set",
						"size": 20
					}
				},
				"package_maintainers_set": {
					"terms": {
						"field": "package_maintainers_set",
						"size": 20
					}
				},
				"package_platforms": {
					"terms": {
						"field": "package_platforms",
						"size": 20
					}
				}
			},
			"global": {}
		},
		"package_attr_set": {
			"terms": {
				"field": "package_attr_set",
				"size": 20
			}
		},
		"package_license_set": {
			"terms": {
				"field": "package_license_set",
				"size": 20
			}
		},
		"package_maintainers_set": {
			"terms": {
				"field": "package_maintainers_set",
				"size": 20
			}
		},
		"package_platforms": {
			"terms": {
				"field": "package_platforms",
				"size": 20
			}
		}
	},
	"from": 0,
	"query": {
		"bool": {
			"filter": [
				{
					"term": {
						"type": {
							"_name": "filter_packages",
							"value": "package"
						}
					}
				},
				{
					"bool": {
						"must": [
							{
								"bool": {
									"should": [
										{
											"term": {
												"package_attr_set": {
													"_name": "filter_bucket_package_attr_set",
													"value": "No package set"
												}
											}
										}
									]
								}
							},
							{
								"bool": {
									"should": []
								}
							},
							{
								"bool": {
									"should": []
								}
							},
							{
								"bool": {
									"should": []
								}
							}
						]
					}
				}
			],
			"must": [
				{
					"dis_max": {
						"queries": [
							{
								"multi_match": {
									"_name": "multi_match_markdown",
									"analyzer": "whitespace",
									"auto_generate_synonyms_phrase_query": false,
									"fields": [
										"package_attr_name^9",
										"package_attr_name.*^5.3999999999999995",
										"package_programs^9",
										"package_programs.*^5.3999999999999995",
										"package_pname^6",
										"package_pname.*^3.5999999999999996",
										"package_description^1.3",
										"package_description.*^0.78",
										"package_longDescription^1",
										"package_longDescription.*^0.6",
										"flake_name^0.5",
										"flake_name.*^0.3"
									],
									"operator": "and",
									"query": "markdown",
									"type": "cross_fields"
								}
							},
							{
								"wildcard": {
									"package_attr_name": {
										"case_insensitive": true,
										"value": "*markdown*"
									}
								}
							}
						],
						"tie_breaker": 0.7
					}
				}
			]
		}
	},
	"size": 50,
	"sort": [
		{
			"_score": "desc",
			"package_attr_name": "desc",
			"package_pversion": "desc"
		}
	]
}
```

**Comment by peterldowns** [comment]
Closing this because I'm not going to work on it, but I'll happily review a contribution if someone does want to implement it the way I've described.

**Comment by tjkirch** [comment]
> Closing this because I'm not going to work on it, but I'll happily review a contribution if someone does want to implement it the way I've described.

Wouldn't it be helpful to have open issues so that people know where contributions are welcome?

**Comment by peterldowns** [comment]
@tjkirch I think it's pretty clear from my responses that contributions are welcome. I don't consider the lack of this feature an issue that needs to be fixed.

**Comment by tjkirch** [comment]
Ok.  I'm just going by my experience, where in most projects closed issues mean disagreement of some sort, and by how GitHub only shows/searches open issues by default.

**Comment by peterldowns** [comment]
I don’t care. Send a PR or stop commenting.
