### ISSUE TITLE
cannot search in different nix channels

### ISSUE THREAD

**Issue by irdaislakhuafa** [peterldowns/nix-search-cli#15]
hi, i've been using nix-search-cli for quite some time now and it's awesome for searching packages from the command line, but i wanted to try searching packages from the command line with sources from other channels but i didn't get anything

first i added new channel with this command 
```bash
nix-channel --add https://channels.nixos.org/nixos-22.11-small nixos-22.11-small
```

and i update channel with this command 
```bash
nix-channel --update
```

then i search package in this channel like this but i didn't get anything
![image](https://github.com/user-attachments/assets/67d0e85e-3bbe-4cec-88f9-ca3d3867afd0)

**Comment by peterldowns** [comment]
Hi, glad to hear you're using and enjoying `nix-search`! This CLI program doesn't interact with your local channels at all; it only searches the Elasticsearch index that powers https://search.nixos.org/packages. The only valid values for `--channel` are `unstable` and whatever pinned version they have on the site, currently `24.05`:

![image](https://github.com/user-attachments/assets/9188698c-8191-4a5d-915e-e5cf83df18e3)

![image](https://github.com/user-attachments/assets/92afd79b-54f4-44cb-929b-68e2ed138e05)

![image](https://github.com/user-attachments/assets/2a7de534-eb25-4a26-88bf-be00aecdfb07)

Sorry for the confusion!

**Comment by peterldowns** [comment]
I updated the cli help command to hopefully make this less confusing for the future:

```bash
# ... on a specific channel, default "unstable". The valid channel
#     values are what the search.nixos.org index has, check
#     that website to see what options they show in their interface.
nix-search --channel=unstable python3
```

**Comment by irdaislakhuafa** [comment]
> I updated the cli help command to hopefully make this less confusing for the future:
> 
> ```shell
> # ... on a specific channel, default "unstable". The valid channel
> #     values are what the search.nixos.org index has, check
> #     that website to see what options they show in their interface.
> nix-search --channel=unstable python3
> ```

haha thanks, i have realize it since a few days ago. sorry for my confusion.

**Comment by peterldowns** [comment]
No problem at all, thanks for writing in. If you have any other questions or suggestions, please let me know.
