### ISSUE TITLE
[Feature] Allow displaying results in reverse order

### ISSUE THREAD

**Issue by jemag** [peterldowns/nix-search-cli#16]
It seems that currently the most relevant results are at the top:
![image](https://github.com/user-attachments/assets/f40ce767-5f01-4338-874f-dc0503863aeb)
I would like to be able to instead have them at the bottom. 

This is especially relevant when using the `--details` flag, which means having to scroll a significant amount to get to the more relevant results

**Comment by peterldowns** [comment]
Thanks for the suggestion — implemented in https://github.com/peterldowns/nix-search-cli/commit/e1227bdd0155070461e592676df61adcde5d0ba2, and will be in the next release.
