### ISSUE TITLE
Getting an error on search

### ISSUE THREAD

**Issue by marcusramberg** [peterldowns/nix-search-cli#6]
```
 error: API failure[index_not_found_exception](index_or_alias=latest-37-nixos-unstable): no such index [latest-37-nixos-unstable]
````

**Comment by devusb** [comment]
Looks like the index may have become prefixed with `latest-39` and/or `latest-40` -- think this corresponds with new revisions of nixos-unstable (for example 40 contains new packages that 39 does not)
```
❯ curl "https://nixos-search-7-1733963800.us-east-1.bonsaisearch.net:443/_aliases?pretty=true" --user aWVSALXpZv:X8gPHnzL52wFEekuxsfQ9cSh | grep latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0      "latest-37-group-manual" : { }
      "latest-38-group-manual" : { }
      "latest-39-nixos-unstable" : { }
      "latest-40-group-manual" : { }
      "latest-35-group-manual" : { }
      "latest-40-nixos-22.11" : { }
      "latest-39-nixos-22.11" : { }
      "latest-36-group-manual" : { }
      "latest-39-group-manual" : { }
      "latest-40-nixos-unstable" : { }
100 49988  100 49988    0     0   182k      0 --:--:-- --:--:-- --:--:--  184k
```
fixing this in `esclient.go` resolves the error, but just replacing it now will likely still result in later recurrence.

**Comment by peterldowns** [comment]
Thanks for the bug report. I agree with the details above -- just need to bump the index, which I'll do shortly.

**Comment by peterldowns** [comment]
@devusb 
> fixing this in esclient.go resolves the error, but just replacing it now will likely still result in later recurrence.

Yeah, unfortunately this is going to happen every time the upstream index changes. I'll try to come up with something smart to auto-increment index numbers and such.

**Comment by peterldowns** [comment]
I applied the temporary fix (bumping the index url from 37 to 40) in https://github.com/peterldowns/nix-search-cli/commit/78d968fcb0ccccbd1915220c8379a0926ae78bb5 and I'll try to come up with a better way of using the `_aliases` endpoint to automatically find the right index in the future. Thanks again @devusb and @marcusramberg for the bug report.

**Comment by peterldowns** [comment]
I was able to figure out a workaround that means that the version number no longer needs to be hardcoded 🥳 

https://github.com/peterldowns/nix-search-cli/commit/14bbb3f67987e19c6d117d569634ec200439940a#diff-b0f433a334d20e27d6371642f9b41f6f5c521aa38eb3b91cedaae81b51354ec7R33

Thank you again for your bug report and suggestion.
