### ISSUE TITLE
This is great. Maybe add it to the official repo?

### ISSUE THREAD

**Issue by nadir-ishiguro** [peterldowns/nix-search-cli#9]
Thank you a lot. This tool is exactly what I was looking for.

It's not to difficult to add it to your config thanks to the flake you provided, but I think this should be part of the official repo.

Others would definitely benefit.

**Comment by peterldowns** [comment]
I'm happy you're using the tool, thanks for writing in. I don't want to bother figuring out how to repackage this in the main nixpkgs repo, I spent a few minutes looking and couldn't find an easy way to reuse the definition from this flake. If you'd like to submit a PR to nixpkgs that does the job properly, I'd be happy to tell them that I approve.

**Comment by nadir-ishiguro** [comment]
I can understand that, as nixpkgs still has no flake support. I'll look into it but I think things are fine as they are.

**Comment by peterldowns** [comment]
OK, in that case I'm going to close this issue for now. I'm happy to revisit this decision in the future if others feel it's important.

**Comment by donovanglover** [comment]
I like things being in nixpkgs so I made a PR here: https://github.com/NixOS/nixpkgs/pull/266689

**Comment by peterldowns** [comment]
@donovanglover that's awesome, thank you!
